# -*- coding: utf-8 -*-
# Generated by Django 1.11b1 on 2019-07-18 09:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Abzac',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('text', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='poem',
            name='text',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Abzac'),
        ),
    ]
