# -*- coding: utf-8 -*-
# Generated by Django 1.11b1 on 2019-07-18 09:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20190718_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abzac',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
