# -*- coding: utf-8 -*-
# Generated by Django 1.11b1 on 2019-07-18 09:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20190718_0917'),
    ]

    operations = [
        migrations.RenameField(
            model_name='abzac',
            old_name='name',
            new_name='people',
        ),
    ]
