# -*- coding: utf-8 -*-
# Generated by Django 1.11b1 on 2019-07-18 09:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20190718_0923'),
    ]

    operations = [
        migrations.AddField(
            model_name='poem',
            name='name',
            field=models.CharField(default="", max_length=30),
            preserve_default=False,
        ),
    ]
