# -*- coding: utf-8 -*-
# Generated by Django 1.11b1 on 2019-07-18 09:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_poem_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poem',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
