# -*- coding: utf-8 -*-
# Generated by Django 1.11b1 on 2019-07-18 10:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20190718_0936'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poem',
            name='text',
        ),
        migrations.AddField(
            model_name='abzac',
            name='poem',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='myapp.Poem'),
            preserve_default=False,
        ),
    ]
