# -*- coding: utf-8 -*-
# Generated by Django 1.11b1 on 2019-07-18 10:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20190718_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='poem',
            name='text',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
