# -*- coding: utf-8 -*-
# Generated by Django 1.11b1 on 2019-07-19 12:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('text_in', models.CharField(max_length=50)),
                ('text_out', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=20)),
                ('status_read', models.BooleanField(default=False)),
                ('status_complate', models.BooleanField(default=False)),
            ],
        ),
    ]
