# Generated by Django 2.1.2 on 2019-07-20 14:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fix', '0002_problem_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='likes',
            field=models.ManyToManyField(related_name='Like', to=settings.AUTH_USER_MODEL),
        ),
    ]
