# Generated by Django 2.1.2 on 2019-07-20 14:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fix', '0003_problem_likes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='problem',
            name='likes',
        ),
        migrations.AddField(
            model_name='like',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fix.Problem'),
        ),
        migrations.AddField(
            model_name='like',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
