# Generated by Django 2.1.2 on 2019-07-20 15:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fix', '0004_auto_20190720_1445'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='state',
        ),
        migrations.AddField(
            model_name='like',
            name='type',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='problem',
            name='like_user',
            field=models.ManyToManyField(related_name='like_user', through='fix.Like', to=settings.AUTH_USER_MODEL),
        ),
    ]
