# Generated by Django 2.1.2 on 2019-07-21 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fix', '0005_auto_20190720_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='type',
            field=models.IntegerField(default=0),
        ),
    ]
